# config/partners.yaml
# Canonical list of API partners to manage via GitHub.
# This file will drive key issuance & rotation automation in the next steps.

partners:
  - subject: "partner-sample"           # must match the Consumer "subject" in Zuplo
    displayName: "Sample Partner"
    contactEmail: "tsikute@gmail.com"
    plan: "standard"                    # free|standard|pro (arbitrary label for your use)
    #rateLimit:                          #per-partner rate-limits are currently turned off (possible put complex to set up)
    #  requestsPerMinute: 50             
    #tags: ["demo", "internal-test"]     # optional labels you’ll reuse in automation
    #notes: "Created initially in the portal; managed by GitOps going forward."

  - subject: "new-cool-partner"
    displayName: "New Cool Partner Inc."
    contactEmail: "trent.sikute@global.church"
    plan: "standard"
    #rateLimit:
    #  requestsPerMinute: 100
    #tags: ["demo", "internal-test"]
    
    # Adding a comment to re-trigger the GitHub Action (run #11).
