# config/partners.yaml
# Canonical list of API partners to manage via GitHub.
# This file will drive key issuance & rotation automation in the next steps.

partners:
  - subject: "partner-sample"           # name assigned to the consumer      
    displayName: "Sample Partner"       # cosmetic display name
    contactEmail: "tsikute@gmail.com"   # email address(es) that have access to the consumer's API key (viewable in the dev portal)
    plan: "standard"                    # free|standard|pro - this is an arbitrary placeholder label we can adjust if tiers of API service are offered.
    rateLimit: 50                       # the number of API requests the consumer can make per minute

  - subject: "new-cool-partner"
    displayName: "New Cool Partner Inc."
    contactEmail: "trent.sikute@global.church"
    plan: "standard"
    rateLimit: 49

  - subject: "paul-martel-api-test"
    displayName: "Paul's Dev Test API"
    contactEmail: "paul.martel@global.church"
    plan: "standard"
    rateLimit: 100

  - subject: "marcus-smith-api-test"
    displayName: "Marcus's Dev Test API"
    contactEmail: "marcus@thesmith.team"
    plan: "standard"
    rateLimit: 52

  - subject: "clayton-fike-api-test"
    displayName: "Clayton's Dev Test API"
    contactEmail: "clayton.fike@global.church"
    plan: "standard"  # This is just a placeholder; plans in the future could be issued with different payment tiers
    rateLimit: 70

# Comment to trigger a re-deployment #1
